### ISSUE TITLE
1.17 doesnt work

### ISSUE THREAD

**Issue by LegacyGamerHD** [luo9674/VGPU#2]
will this be fixed with your lib

**Comment by luo9674** [comment]
> 这会用你的库修复吗



> will this be fixed with your lib

I'm not sure, because I'm using 1.12.2. 
and if I use GLSL 3.2 on a higher version of MC, I'll have to discard many of the GLSL 2.0 built-in variables and functions that gl4es provides now. 
Of course, since ESSL3.x itself is based on GLSL3.3 +, support GLSL3.3 + (including API) may be easier to do. but now I don't pay attention to this, I am prioritizing MC1.12.2. MRT and GLSL 2.0 built-in functions support by using ESSL3.x.
Maybe I'll think about it when the present work is done.

**Comment by luo9674** [comment]
I'm not sure, because I'm using MC 1.12.2.
If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, I don't judge and separate the GLSL version of the Shader declaration, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
Maybe I'll think about it after the present work is done.

**Comment by luo9674** [comment]
> will this be fixed with your lib

I'm not sure, because I'm using MC 1.12.2.
If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)

Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
Maybe I'll think about it after the present work is done.

**Comment by LegacyGamerHD** [comment]
> > will this be fixed with your lib
> 
> I'm not sure, because I'm using MC 1.12.2.
> If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
> 
> Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
> Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
> While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
> Maybe I'll think about it after the present work is done.

well it says it couldnt reload the shader i can provide a log

**Comment by luo9674** [comment]
> > > will this be fixed with your lib
> > 
> > 
> > I'm not sure, because I'm using MC 1.12.2.
> > If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
> > Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
> > Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
> > While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
> > Maybe I'll think about it after the present work is done.
> 
> well it says it couldnt reload the shader i can provide a log

I tested it and MC1.16.3 renders fine.

**Comment by LegacyGamerHD** [comment]
> > > > will this be fixed with your lib
> > > 
> > > 
> > > I'm not sure, because I'm using MC 1.12.2.
> > > If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
> > > Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
> > > Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
> > > While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
> > > Maybe I'll think about it after the present work is done.
> > 
> > 
> > well it says it couldnt reload the shader i can provide a log
> 
> I tested it and MC1.16.3 renders fine.

Yes but 1.17 doesn't at least without the converted texturepack

**Comment by luo9674** [comment]
> > > > > will this be fixed with your lib
> > > > 
> > > > 
> > > > I'm not sure, because I'm using MC 1.12.2.
> > > > If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
> > > > Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
> > > > Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
> > > > While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
> > > > Maybe I'll think about it after the present work is done.
> > > 
> > > 
> > > well it says it couldnt reload the shader i can provide a log
> > 
> > 
> > I tested it and MC1.16.3 renders fine.
> 
> Yes but 1.17 doesn't at least without the converted texturepack

Texture processing is mainly provided by gl4es, can gl4es render 1.17?

**Comment by LegacyGamerHD** [comment]
> > > > > > will this be fixed with your lib
> > > > > 
> > > > > 
> > > > > I'm not sure, because I'm using MC 1.12.2.
> > > > > If MC1.17 uses GLSL 3.2, the failure is mostly due to incompatibility of GLSL built-in variables.(If 1. 17 uses GLSL 2. 0, then it's the GLSL built-in functions, which I'm currently fixing.)
> > > > > Because the VGPU still uses GL4ES to provide the default GLSL2.0 built-in variable, and vgpu does not currently have a converter implementation for GLSL 3.x, so the VGPU is now only available for ESSL3.x-based GLSL2.0.
> > > > > Of course, ESSL 3.x itself is based on GLSL 3.3 +, so the transition between them may be easier to do.
> > > > > While I'm not thinking about it right now, I'm working on building support for GLSL 2.0 MRT and built-in functions using ESSL 3.x.
> > > > > Maybe I'll think about it after the present work is done.
> > > > 
> > > > 
> > > > well it says it couldnt reload the shader i can provide a log
> > > 
> > > 
> > > I tested it and MC1.16.3 renders fine.
> > 
> > 
> > Yes but 1.17 doesn't at least without the converted texturepack
> 
> Texture processing is mainly provided by gl4es, can gl4es render 1.17?

gl4es can render when shaders are converted to a lower version of opengl

**Comment by luo9674** [comment]
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6885653/latestlog.txt)

This log shows gl4es 1.15, not vgpu 1.2.

**Comment by luo9674** [comment]
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6885653/latestlog.txt)

Shader for 1. 17 uses some gl4es unconverted built-in functions, resulting in an error.

**Comment by LegacyGamerHD** [comment]
> > [latestlog.txt](https://github.com/luo9674/VGPU/files/6885653/latestlog.txt)
> 
> Shader for 1. 17 uses some gl4es unconverted built-in functions, resulting in an error.

righ i forgot it set the gl4es auto

**Comment by LegacyGamerHD** [comment]
nvm it still doesnt work

**Comment by LegacyGamerHD** [comment]
[latestlog.txt](https://github.com/luo9674/VGPU/files/6885744/latestlog.txt)

**Comment by luo9674** [comment]
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6885744/latestlog.txt)

Well, so far it looks like there are only two shader compilation errors, UV2/256.0, where the l-value is an integer type and the r-value is a floating type, and the implicit type conversion causes the error. I can try to fix this error by adding a vec2 constructor.Maybe in half a day or a day I can upload a little new version.

**Comment by luo9674** [comment]
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6885744/latestlog.txt)

In addition, because 1.17 uses GLSL3.2, it does not use the built-in variables of glsl2.0, so gl4es does not participate in the conversion of built-in variables, but directly uses the default ESSL3.2, so that most shaders have no compilation errors. It seems that this can save some work.

**Comment by LegacyGamerHD** [comment]
great

**Comment by LegacyGamerHD** [comment]
@luo9674 still 1.17 doesnt work here is log btw am not usinf artdevs asets patch
[latestlog.txt](https://github.com/luo9674/VGPU/files/6908519/latestlog.txt)

**Comment by luo9674** [comment]
> @luo9674 still 1.17 doesnt work here is log btw am not usinf artdevs asets patch
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6908519/latestlog.txt)

Well, it's just a little text error, and I'll fix it soon.

**Comment by LegacyGamerHD** [comment]
> > @luo9674 still 1.17 doesnt work here is log btw am not usinf artdevs asets patch
> > [latestlog.txt](https://github.com/luo9674/VGPU/files/6908519/latestlog.txt)
> 
> Well, it's just a little text error, and I'll fix it soon.

btw thats with optifine without that i get 

`I/LIBGL   ( 2352): ERROR: 0:23: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion)
I/LIBGL   ( 2352): ERROR: 0:23: 'texelFetch' : no matching overloaded function found 
I/LIBGL   ( 2352): ERROR: 0:26: '�' : Unknown char 
I/LIBGL   ( 2352): ERROR: 0:26: '�' : Syntax error:  syntax error
I/LIBGL   ( 2352): ERROR: 4 compilation errors.  No code generated.`

**Comment by LegacyGamerHD** [comment]
and this is 1.17.1

`I/LIBGL   ( 3770): ERROR: 0:23: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion)
I/LIBGL   ( 3770): ERROR: 0:23: 'texelFetch' : no matching overloaded function found 
I/LIBGL   ( 3770): ERROR: 2 compilation errors.  No code generated.`

**Comment by luo9674** [comment]
> and this is 1.17.1
> 
> `I/LIBGL ( 3770): ERROR: 0:23: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion) I/LIBGL ( 3770): ERROR: 0:23: 'texelFetch' : no matching overloaded function found I/LIBGL ( 3770): ERROR: 2 compilation errors. No code generated.`

Ok, these are implicit type conversions, which is allowed in the GLSL specification but in ESSL is not allowed, I have been building a general type converter, now it is complete.

**Comment by LegacyGamerHD** [comment]
@luo9674 rude qeastion why dont publis source code of every update so pojav can make a auto upstreamer

**Comment by LegacyGamerHD** [comment]
> > and this is 1.17.1
> > `I/LIBGL ( 3770): ERROR: 0:23: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion) I/LIBGL ( 3770): ERROR: 0:23: 'texelFetch' : no matching overloaded function found I/LIBGL ( 3770): ERROR: 2 compilation errors. No code generated.`
> 
> Ok, these are implicit type conversions, which is allowed in the GLSL specification but in ESSL is not allowed, I have been building a general type converter, now it is complete.

Any news?

**Comment by luo9674** [comment]
> > > and this is 1.17.1
> > > `I/LIBGL ( 3770): ERROR: 0:23: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion) I/LIBGL ( 3770): ERROR: 0:23: 'texelFetch' : no matching overloaded function found I/LIBGL ( 3770): ERROR: 2 compilation errors. No code generated.`
> > 
> > 
> > Ok, these are implicit type conversions, which is allowed in the GLSL specification but in ESSL is not allowed, I have been building a general type converter, now it is complete.
> 
> Any news?

Right now I'm debugging the converter and working on some details. Some shaders with implicit type conversions are already running on the VGPU. The new vgpu will be released soon.

**Comment by LegacyGamerHD** [comment]
> > > > and this is 1.17.1
> > > > `I/LIBGL ( 3770): ERROR: 0:23: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type '2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion) I/LIBGL ( 3770): ERROR: 0:23: 'texelFetch' : no matching overloaded function found I/LIBGL ( 3770): ERROR: 2 compilation errors. No code generated.`
> > > 
> > > 
> > > Ok, these are implicit type conversions, which is allowed in the GLSL specification but in ESSL is not allowed, I have been building a general type converter, now it is complete.
> > 
> > 
> > Any news?
> 
> Right now I'm debugging the converter and working on some details. Some shaders with implicit type conversions are already running on the VGPU. The new vgpu will be released soon.

you said soon but ehh its 3 days later sorry forbeing inpatient

**Comment by LegacyGamerHD** [comment]
@luo9674 1.17 doesnt work still i get `I/LIBGL  (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `

**Comment by luo9674** [comment]
> @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `

i need a log.

**Comment by luo9674** [comment]
> @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `

Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.

**Comment by LegacyGamerHD** [comment]
> > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> 
> Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.

your latet comit works almost but it crashes with artdev said 'tis He needs to implement glVertexAttribIPointer'


`[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

**Comment by luo9674** [comment]
> > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > 
> > 
> > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> 
> your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> 
> `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

That API now calls the implementation provided by gl4es.

**Comment by luo9674** [comment]
> > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > 
> > 
> > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> 
> your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> 
> `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.

**Comment by LegacyGamerHD** [comment]
> > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > 
> > > 
> > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > 
> > 
> > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> 
> Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.

yes as this is still happning were so close do to 1.17

**Comment by LegacyGamerHD** [comment]
> > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > 
> > > > 
> > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > 
> > > 
> > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > 
> > 
> > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
[latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)

> 
> yes as this is still happning were so close do to 1.17

**Comment by LegacyGamerHD** [comment]
> > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > 
> > > > > 
> > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > 
> > > > 
> > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > 
> > > 
> > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> 
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> 
> yes as this is still happning were so close do to 1.17 above the full log and the error below
> 
> `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

@luo9674  did you found out what the last one is

**Comment by luo9674** [comment]
> > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > 
> > > > > > 
> > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > 
> > > > > 
> > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > 
> > > > 
> > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > 
> > 
> > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> 
> @luo9674 did you found out what the last one is

The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.

**Comment by LegacyGamerHD** [comment]
> > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > 
> > > > > > > 
> > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > 
> > > > > > 
> > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > 
> > > > > 
> > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > 
> > > 
> > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > 
> > 
> > @luo9674 did you found out what the last one is
> 
> The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.

The latest build crashes ever time

**Comment by luo9674** [comment]
> > > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > > 
> > > > > > > 
> > > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > 
> > > > > > 
> > > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > > 
> > > > 
> > > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > 
> > > 
> > > @luo9674 did you found out what the last one is
> > 
> > 
> > The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.
> 
> The latest build crashes ever version


1.17?
I want to look at the log.

**Comment by LegacyGamerHD** [comment]
[latestlog.txt](https://github.com/luo9674/VGPU/files/6952728/latestlog.txt)
Well here it's 1.12 btw

**Comment by LegacyGamerHD** [comment]
@luo9674

**Comment by LegacyGamerHD** [comment]
> > > > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > > 
> > > > > > > 
> > > > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > > > 
> > > > > 
> > > > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > 
> > > > 
> > > > @luo9674 did you found out what the last one is
> > > 
> > > 
> > > The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.
> > 
> > 
> > The latest build crashes ever version
> 
> 1.17?
> I want to look at the log.

Here is 1.16 
[latestlog.txt](https://github.com/luo9674/VGPU/files/6952757/latestlog.txt)

**Comment by luo9674** [comment]
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6952728/latestlog.txt)
> Well here it's 1.12 btw

I forced LIBGL_NORMALIZE open.

**Comment by luo9674** [comment]
> > > > > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > > > > 
> > > > > > 
> > > > > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > > > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > > > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > 
> > > > > 
> > > > > @luo9674 did you found out what the last one is
> > > > 
> > > > 
> > > > The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.
> > > 
> > > 
> > > The latest build crashes ever version
> > 
> > 
> > 1.17?
> > I want to look at the log.
> 
> Here is 1.16
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6952757/latestlog.txt)

**Comment by luo9674** [comment]
> > > > > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > > > > 
> > > > > > 
> > > > > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > > > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > > > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > 
> > > > > 
> > > > > @luo9674 did you found out what the last one is
> > > > 
> > > > 
> > > > The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.
> > > 
> > > 
> > > The latest build crashes ever version
> > 
> > 
> > 1.17?
> > I want to look at the log.
> 
> Here is 1.16
> [latestlog.txt](https://github.com/luo9674/VGPU/files/6952757/latestlog.txt)

They(1.12.2 and 1.16.4 with OptiFine) all work fine on my device. I have to add debugging to your device.
I don't know if it's your pojav environment or an automated build that's causing the crash, but maybe you can try adding my compiled library directly to pojav temporarily.

**Comment by LegacyGamerHD** [comment]
> > > > > > > > > > > > @luo9674 1.17 doesnt work still i get `I/LIBGL (23787): ERROR: 0:32: 'texelFetch' : no matching overloaded function found `
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Well, before that I have solved a similar problem. I will add a fix. I will update it in the source code.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > your latet comit works almost but it crashes with artdev said tis `He needs to implement glVertexAttribIPointer`
> > > > > > > > > > `[0805/154700.806443:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1) [0805/154700.820397:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Yes, I'll take a look. Now the API calls directly into the native gles3.2 API.
> > > > > > > 
> > > > > > > 
> > > > > > > [latestlog.txt](https://github.com/luo9674/VGPU/files/6940161/latestlog.txt)
> > > > > > > yes as this is still happning were so close do to 1.17 above the full log and the error below
> > > > > > > `[0805/181721.906389:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`
> > > > > > 
> > > > > > 
> > > > > > @luo9674 did you found out what the last one is
> > > > > 
> > > > > 
> > > > > The log is running 1.3.0, and I updated some of the content in 1.3.5. Also, I'm rebuilding a new translator for the GL3.2 + core profile, which may take some time. I'm also working for MRT at GLSL.
> > > > 
> > > > 
> > > > The latest build crashes ever version
> > > 
> > > 
> > > 1.17?
> > > I want to look at the log.
> > 
> > 
> > Here is 1.16
> > [latestlog.txt](https://github.com/luo9674/VGPU/files/6952757/latestlog.txt)
> 
> They(1.12.2 and 1.16.4 with OptiFine) all work fine on my device. I have to add debugging to your device.
> I don't know if it's your pojav environment or an automated build that's causing the crash, but maybe you can try adding my compiled library directly to pojav temporarily.

its fixed after the latest commit 1.17 still doesnt work do it crashes still with a `0809/180023.196672:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

**Comment by LegacyGamerHD** [comment]
@luo9674  i got it semi working with artdev texture pack and useing gles 2.0 i got in the main menu do it crashes on a world with artdev texture pack 
[latestlog (1).txt](https://github.com/luo9674/VGPU/files/6986549/latestlog.1.txt)

![Screenshot_20210814-145955](https://user-images.githubusercontent.com/25864932/129448290-d321be9e-7f56-4eab-a636-1209ffc6cb55.jpg)

**Comment by luo9674** [comment]
> @luo9674 i got it semi working with artdev texture pack and useing gles 2.0 i got in the main menu do it crashes on a world with artdev texture pack
> [latestlog (1).txt](https://github.com/luo9674/VGPU/files/6986549/latestlog.1.txt)
> 
> ![Screenshot_20210814-145955](https://user-images.githubusercontent.com/25864932/129448290-d321be9e-7f56-4eab-a636-1209ffc6cb55.jpg)

The same is true for my tests, and it looks like this could be a problem with the API causing the resource to fail to load, or it could be a shader(It may use the operator %) compilation failure. Although the API for GL 3.x has some wrappers. But I'm still mainly working on supporting GLSL120-140.

**Comment by LegacyGamerHD** [comment]
@luo9674 Any news on your work

**Comment by luo9674** [comment]
> @luo9674 Any news on your work

I have other things to do for the next period of time, I guess I can't continue to work on it, and there should be no new progress on GLAPI in a short time.
I'm also looking at Vulkan and zink because packaging into a full GL 3.x + API is a complex thing for GLES. (Although it may be easier on shader)
